
# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 999
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（一天，单位分钟）
  expireTime: 1440

# Spring配置
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
